# -*- coding: utf-8 -*-
"""formulario.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZTUaUBborPNJ90qX9pQc8Dg1axVt_rgA
"""

import streamlit as st
import gspread
from google.oauth2.service_account import Credentials
from datetime import datetime

# =====================
# CONFIGURAÇÕES
# =====================
SHEET_ID = "11JaCc4y-htBW-cxbvbMBV28GHYlORbMM6345TSaXcgQ"
NOME_ABA = "Respostas"  # confirme o nome da aba no Google Sheets

scope = [
    "https://www.googleapis.com/auth/spreadsheets",
    "https://www.googleapis.com/auth/drive"
]

# =====================
# GOOGLE SHEETS
# =====================
service_account_info = dict(st.secrets["gcp_service_account"])

credentials = Credentials.from_service_account_info(
    service_account_info,
    scopes=scope
)

gc = gspread.authorize(credentials)
sheet = gc.open_by_key(SHEET_ID).worksheet(NOME_ABA)

# =====================
# INTERFACE
# =====================
st.title("Checklist Operacional")

with st.form("checklist_form"):

    # ---- Identificação
    st.subheader("Identificação")

    gerente = st.text_input("Gerente Comercial")
    coordenador = st.text_input("Coordenador Regional")
    supervisor = st.text_input("Supervisor de Loja")
    loja = st.text_input("Loja")

    st.divider()

    # ---- Perguntas
    st.subheader("Perguntas")

    perguntas = [
        "01. O Supervisor de Loja realiza o acompanhando dos relatórios disponíveis no D-1 e INTRADAY e participa sua equipe dos mesmos?",
        "02. O Supervisor de Loja acompanha e tem ciência de todas as pendências de contrato, e propostas negadas?",
        "03. O Supervisor de Loja possui de forma clara e objetiva o controle da informação de acionamentos?",
        "04. O Supervisor de Loja está engajado e envolvido com as ações de treinamento em loja desenvolvidas e orientadas pela empresa?",
        "05. A loja está em ordem nos quesitos estrutura física, estado de conservação, limpeza e organização em geral, layout da fachada e calçada, toldos, tapetes, iluminação e ar condicionado?",
        "06. O Supervisor de Loja possui disciplina e foco com as atividades principais do programa, método de atendimento e Vendas FACTA e ferramentas?",
        "07. O Supervisor de Loja tem total ciência dos principais erros de processos cometidos por seus Consultores e que geram recusas na mesa de crédito?",
        "08. A equipe na loja conhece e domina todos os campos e funcionalidades de todos os sistemas operacionais?",
        "09. A equipe da loja possui boa apresentação pessoal, de acordo com as políticas e normas de conduta da empresa?",
        "10. O Supervisor de Loja organiza e acompanha diariamente o rodízio de acionamentos de sua equipe?",
        "11. O Supervisor de Loja tem ciência do licenciamento e regularização de sua loja?",
        "12. O Supervisor de Loja tem acompanhado os comunicados internos e orientado sua equipe?",
        "13. Os Consultores sabem sua meta diária, ticket médio e acionamentos necessários?",
        "14. O Supervisor de Loja acompanha e treina diariamente os Consultores?",
        "15. O Supervisor de Loja realiza reuniões diárias de resultados?",
        "16. Os Consultores sabem informar sua meta diária e acumulado do mês?",
        "17. Os Consultores conhecem os indicadores de vendas?",
        "18. O Supervisor de Loja realiza planos de treinamento customizados?",
        "19. A equipe sabe destacar características e benefícios dos produtos?",
        "20. A equipe sabe destacar as vantagens e benefícios da empresa?",
        "21. O Supervisor de Loja conhece os indicadores de inadimplência?",
        "22. O Supervisor atua ativamente nos indicadores de inadimplência e retenção?",
        "23. O Supervisor acompanha o não pagamento da 1ª parcela?",
        "24. O Supervisor atua sobre os saldos de portabilidade?",
        "25. O Supervisor faz a gestão de posições disponíveis x vagas abertas?",
        "26. O Supervisor conhece a particularidade da carteira de clientes?",
        "27. A equipe mantém assiduidade em loja?",
        "28. A equipe domina técnicas de neutralização de objeções?",
        "29. A equipe realiza cross sell de produtos?",
        "30. O Supervisor promove treinamentos de produtos e métodos?",
        "31. Os Consultores pedem indicação ao final do atendimento?",
        "32. A equipe está em dia com treinamentos obrigatórios?",
        "33. O Supervisor faz a gestão de horas extras?",
        "34. O Supervisor presta contas do caixa da loja?"
    ]

    respostas = []

    for i, pergunta in enumerate(perguntas, start=1):
        resposta = st.radio(
            pergunta,
            ["Sim", "Não"],
            horizontal=True,
            key=f"q{i}"
        )
        respostas.append(resposta)

    st.divider()

    enviar = st.form_submit_button("Enviar Checklist")

# =====================
# SALVAR NO GOOGLE SHEETS
# =====================
if enviar:
    if not all([gerente, coordenador, supervisor, loja]):
        st.error("⚠️ Preencha todos os campos de identificação.")
    else:
        linha = [
            datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            gerente,
            coordenador,
            supervisor,
            loja,
            *respostas
        ]

        sheet.append_row(linha)
        st.success("Checklist enviado com sucesso ✅")